$background = 040405
$onBackground = e5e1e3
$surface = 040405
$surfaceDim = 040405
$surfaceBright = 101010
$surfaceContainerLowest = 030303
$surfaceContainerLow = 080708
$surfaceContainer = 090909
$surfaceContainerHigh = 0c0c0c
$surfaceContainerHighest = 0f0f0f
$onSurface = e5e1e3
$surfaceVariant = 141314
$onSurfaceVariant = c7c5cd
$outline = 919097
$outlineVariant = 46464c
$inverseSurface = e5e1e3
$inverseOnSurface = 313032
$shadow = 000000
$scrim = 000000
$surfaceTint = 28282a
$primary = c3c5dd
$primaryDim = e3e3fd
$onPrimary = 2d2f42
$primaryContainer = 717389
$onPrimaryContainer = fffbff
$inversePrimary = 5b5d72
$primaryFixed = e0e1fa
$primaryFixedDim = c3c5dd
$onPrimaryFixed = 181a2c
$onPrimaryFixedVariant = 43455a
$secondary = c7c5d0
$secondaryDim = e3e1ec
$onSecondary = 2f3038
$secondaryContainer = 46464f
$onSecondaryContainer = b5b4bf
$secondaryFixed = e3e1ec
$secondaryFixedDim = c7c5d0
$onSecondaryFixed = 1a1b23
$onSecondaryFixedVariant = 46464f
$tertiary = ddbed0
$tertiaryDim = fddcef
$onTertiary = 3f2a38
$tertiaryContainer = 876d7d
$onTertiaryContainer = fffbff
$tertiaryFixed = fadaec
$tertiaryFixedDim = ddbed0
$onTertiaryFixed = 281622
$onTertiaryFixedVariant = 57404f
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 74768c
$secondaryPaletteKeyColor = 767680
$tertiaryPaletteKeyColor = 876d7d
$neutralPaletteKeyColor = 787678
$neutralVariantPaletteKeyColor = 77767d
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 74768c
$secondary_paletteKeyColor = 767680
$tertiary_paletteKeyColor = 876d7d
$neutral_paletteKeyColor = 787678
$neutral_variant_paletteKeyColor = 77767d
$term0 = 080808
$term1 = a178ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 95abd7
$term5 = aea0ec
$term6 = 9dceff
$term7 = e8d3de
$term8 = ac9fa9
$term9 = b797ff
$term10 = 89ecff
$term11 = fff0f6
$term12 = b3c2dc
$term13 = c4b6f6
$term14 = bae0ff
$term15 = ffffff
$rosewater = f6eff9
$flamingo = e7def4
$pink = ded8ff
$mauve = b9baff
$red = baa8ff
$maroon = c4b7ee
$peach = e0c2f9
$yellow = ffecf3
$green = c8e3ff
$teal = d0e0ff
$sky = ccdbff
$sapphire = b2c6ff
$blue = aab9ff
$lavender = c3c9ff
$klink = 6984d1
$klinkSelection = 6c83d1
$kvisited = 7675dc
$kvisitedSelection = 7a74dc
$knegative = 926eff
$knegativeSelection = 976cff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 5baeff
$kpositiveSelection = 60adff
$text = e5e1e3
$subtext1 = c7c5cd
$subtext0 = 919097
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161616
$surface2 = 121212
$surface1 = 0e0d0d
$surface0 = 060607
$base = 000001
$mantle = 000001
$crust = 000001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
