set-option -sa terminal-overrides ",xterm*:Tc"
set -as terminal-features ",xterm*:RGB:extkeys"
set -s extended-keys on
set -g mouse on
set -g status-interval 5

# Set Prefix
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Start indexing at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Status bar position
set-option -g status-position top

# THEME INTEGRATION
init_bg="#161423"
init_surface="#201D33"
init_border="#322D4A"
init_text_primary="#E0DEF4"
init_text_secondary="#908CAA"
init_text_muted="#6E6A86"
init_accent="#A277FF" 

# Status Bar Base
set -g status-style "bg=$init_bg,fg=$init_text_secondary"
set -g status-left-length 50
set -g status-right-length 100 

# Pane Borders
set -g pane-border-style "fg=$init_border"
set -g pane-active-border-style "fg=$init_accent"

# Status Left (Session Name)
set -g status-left "#[fg=$init_bg,bg=$init_accent,bold] #S #[bg=default,fg=$init_accent] "

# Status Right (System Monitor & Clock)
# This uses the tmux-cpu plugin variables
set -g status-right "#[fg=$init_text_muted] Ram: #{ram_percentage} #[fg=$init_text_muted,bg=$init_surface] %H:%M "

# Window Status (Tabs)
setw -g window-status-format "#[fg=$init_text_muted] #I:#W "
setw -g window-status-current-format "#[fg=$init_accent,bg=$init_surface] #I:#W "
setw -g window-status-separator ""

# Message Style
set -g message-style "fg=$init_accent,bg=$init_surface,bold"

# NAVIGATION & KEYBINDINGS
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n S-Left  previous-window
bind -n S-Right next-window

bind -n M-H previous-window
bind -n M-L next-window

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# PLUGINS (TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'

run '~/.tmux/plugins/tpm/tpm'
