-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "14")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "14")

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.75,
        blur = {
            brightness = 1.05,
            contrast = 0.9,
            noise = 0.014,
            passes = 4,
            vibrancy = 0.35,
            xray = true,
        },
        dim_special = 0.15,
        fullscreen_opacity = 0.75,
        inactive_opacity = 0.55,
        rounding = 8,
    },
    general = {
        layout = "master",
    },
})

-- Keybinds
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.focus({ direction = "right" }))
hl.unbind("SUPER + K")
hl.bind("SUPER + K", hl.dsp.focus({ direction = "up" }))
hl.unbind("SUPER + H")
hl.bind("SUPER + H", hl.dsp.focus({ direction = "left" }))
hl.unbind("SUPER + J")
hl.bind("SUPER + J", hl.dsp.focus({ direction = "down" }))
hl.unbind("SUPER + CTRL + L")
hl.bind("SUPER + CTRL + L", hl.dsp.exec_cmd("noctalia msg session lock"))
